package GUI;

import javax.swing.*;
import java.awt.*;

public class Main_Form extends JFrame {
    JButton n1=new JButton("Menu 1");
    JButton n2=new JButton("Menu 2");
    JButton n3=new JButton("Menu 3");
    JButton n4=new JButton("Menu 4");
    JButton n11=new JButton("Menu 1");
    JButton n12=new JButton("Menu 2");
    JButton n13=new JButton("Menu 3");
    JButton n14=new JButton("Menu 4");
    JLabel bn1=new JLabel("Menu 1");
    JLabel bn2=new JLabel("Menu 2");
    JLabel bn3=new JLabel("Menu 3");
    JLabel bn4=new JLabel("Menu 4");
    JButton b1,b2;
    JTextField t1;
    JPasswordField t2;
    JLabel l1,l2,l3,l4,l5;
    JRadioButton r1=new JRadioButton("Male");
    JRadioButton r2=new JRadioButton("Female");
    JRadioButton r3=new JRadioButton("single");
    JRadioButton r4=new JRadioButton("Married");
    ButtonGroup g1=new ButtonGroup();
    ButtonGroup g2=new ButtonGroup();
    JCheckBox c1=new JCheckBox("CG");
    JCheckBox c2=new JCheckBox("CA");
    JCheckBox c3=new JCheckBox("SA");
    JCheckBox c4=new JCheckBox("DB");
    JCheckBox c5=new JCheckBox("CV");
    JMenu m1=new JMenu("File");
    JMenu m2=new JMenu("Edit");
    JMenu m3=new JMenu("Help");
JMenuBar bb1=new JMenuBar();

    public  Main_Form(){
        this.setTitle("Form");
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setSize(500,700);
        this.setLocation(200,50);
        this.setLayout(null);
        b1=new JButton("save");
        b2=new JButton("show");
        t1=new JTextField();
        t2=new JPasswordField();
        l1=new JLabel("full name");
        l2=new JLabel("password");
        l3=new JLabel("Gender: ");
        l4=new JLabel("status: ");
        l5=new JLabel("Material: ");
        l1.setBounds(150,50,100,25);
        t1.setBounds(220,50,150,25);
        this.add(l1);
        this.add(t1);
        l2.setBounds(150,90,100,25);
        t2.setBounds(220,90,150,25);
        this.add(l2);
        this.add(t2);
        b1.setBounds(170,130,75,25);
        b2.setBounds(280,130,75,25);
        this.add(b1);
        this.add(b2);
        r1.setBounds(100,200,100,25);
        r2.setBounds(270,200,100,25);
        r3.setBounds(100,250,100,25);
        r4.setBounds(270,250,100,25);
        l3.setBounds(10,200,90,25);
        l4.setBounds(10,250,90,25);
        g1.add(r1);
        g1.add(r2);
        g2.add(r3);
        g2.add(r4);
        this.add(r1);
        this.add(r2);
        this.add(r3);
        this.add(r4);
        this.add(l3);
        this.add(l4);
        l5.setBounds(10,300,90,25);
        this.add(l5);
        c1.setBounds(70,300,50,25);
        this.add(c1);
        c2.setBounds(140,300,50,25);
        this.add(c2);
        c3.setBounds(210,300,50,25);
        this.add(c3);
        c4.setBounds(280,300,50,25);
        this.add(c4);
        c5.setBounds(350,300,50,25);
        this.add(c5);
        m1.add(n1);
        m1.add(n2);
        m1.add(n3);
        m1.add(n4);
        m2.add(n11);
        m2.add(n12);
        m2.add(n13);
        m2.add(n14);
        m3.add(bn1);
        m3.add(bn2);
        m3.add(bn3);
        m3.add(bn4);
        bb1.add(m1);
        bb1.add(m2);
        bb1.add(m3);
        n1.setBackground(Color.red);
        n1.setForeground(Color.YELLOW);
        n2.setBackground(Color.red);
        n2.setForeground(Color.YELLOW);
        n3.setBackground(Color.red);
        n3.setForeground(Color.YELLOW);
        n4.setBackground(Color.red);
        n4.setForeground(Color.YELLOW);
        bb1.setBounds(0,0,500,30);
        this.add(bb1);
    }
}
